### PR TITLE
added artists page, fixed navigation links

### LINKED ISSUE #24: library navigation links
I need to fix the navigational links at the top of the library page. This will include proper CSS for hover effects and the links will be functional to their url location.

### PR DESCRIPTION
**Pull request by chelsey-g**
1. I have created the 'Artists' category page within 'Library' page. 
2. I have fixed the top navigation links so they are fully functional, fixes #24 issue.

### CODE REVIEW

File: src/pages/ArtistsCollectionPage.jsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+  return (
+    <ArtistsCollectionView
+      followedArtists={followedArtists}
+      artists={props.artists}
+    />
+  );
+}
+
+ArtistsCollectionPage.propTypes = {
+  followedArtists: PropTypes.array,
```
Comment (phishy) [inline src/pages/ArtistsCollectionPage.jsx:33]: Doesn't seem to me that `followedArtists` is a prop you pass into this component. Howwever, it does look like you are using `props.artists`

File: src/components/ArtistMediumCardCollection.jsx [hunk 2]
```diff
@@ -0,0 +1,17 @@
+import ArtistsMediumCard from "./ArtistsMediumCard";
+import "./ArtistMediumCardCollection.css";
+import PropTypes from "prop-types";
+
+export default function ArtistMediumCardCollection(artists) {
+  return (
+    <div className="artists-collection">
+      {artists.followedArtists.map((artist) => (
```
Comment (phishy) [inline src/components/ArtistMediumCardCollection.jsx:8]: This is a little misleading. You have a proptype defined called artist, but really you're using artists.followedArtists`.. You might want to dereference that one level up so that artists is alll you would really need.

File: src/components/ArtistsCollectionView.jsx [hunk 3]
```diff
@@ -0,0 +1,35 @@
+import "./ArtistsCollectionView.css";
+import UserMenuButton from "./UserMenuButton";
+import LibraryTabNav from "./LibraryTabNav";
+import LeftArrowButton from "./LeftArrowButton";
+import RightArrowButton from "./RightArrowButton";
+import { PropTypes } from "prop-types";
+import ArtistMediumCardCollection from "./ArtistMediumCardCollection";
+
+export default function ArtistsCollectionView(props) {
+  let { followedArtists } = props;
```
Comment (phishy) [inline src/components/ArtistsCollectionView.jsx:10]: This is unused code as indicated by vscode since you are using the prop directly.

File: src/components/ArtistsCollectionView.jsx [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+      </div>
+      <div className="library-view-title-header">Artists</div>
+      <div className="playlist-view-content">
+        {/* <ArtistsMediumCard followedArtists={followedArtists[0]} /> */}
+        <ArtistMediumCardCollection followedArtists={props.followedArtists} />
+      </div>
+    </div>
+  );
+
+  ArtistsCollectionView.propTypes = {
```
Comment (phishy) [inline src/components/ArtistsCollectionView.jsx:32]: This is accidentally defined inside the component, and vscode errors register it as unreachable.

**Review by phishy — CHANGES_REQUESTED** [review]
Looking good, left a few notes.

**Review by chelsey-g — COMMENTED** [review]
fixed all the small issues within your notes
